import { TrendingVideo } from './types';

export const CURATED_TRENDING_VIDEOS: TrendingVideo[] = [
  {
    title: 'O Poder da Disciplina (com Renato Cariani) | Os Sócios Podcast',
    channel: 'Os Sócios Podcast',
    videoId: 'B57eOqeLVfc',
    url: 'https://www.youtube.com/watch?v=B57eOqeLVfc',
    duration: '2h 15min',
    viralityScore: 98,
    reason: 'Ganchos poderosos sobre disciplina militar, foco inabalável e rotinas de alta performance.',
    suggestedThemes: ['Disciplina', 'Foco', 'Dopamina', 'Hábitos'],
  },
  {
    title: 'PrimoCast: Como Construir Riqueza e Negócios Escaláveis',
    channel: 'PrimoCast',
    videoId: '2ZIpFytCSVc',
    url: 'https://www.youtube.com/watch?v=2ZIpFytCSVc',
    duration: '1h 55min',
    viralityScore: 95,
    reason: 'Declarações financeiras contra-intuitivas que geram debate imediato nos comentários e alta taxa de salvamento.',
    suggestedThemes: ['Finanças', 'Negócios', 'Mentalidade', 'Vendas'],
  },
  {
    title: 'Huberman Lab: How to Optimize Your Brain Chemistry & Focus',
    channel: 'Andrew Huberman',
    videoId: 'QmOF0crdyRU',
    url: 'https://www.youtube.com/watch?v=QmOF0crdyRU',
    duration: '2h 18min',
    viralityScore: 98,
    reason: 'Protocolos acionáveis de 1 minuto perfeitos para prender a atenção e gerar compartilhamentos com amigos.',
    suggestedThemes: ['Biohacking', 'Produtividade', 'Sono', 'Foco'],
  },
  {
    title: 'Lex Fridman Podcast: Sam Altman on AI and the Future of Humanity',
    channel: 'Lex Fridman',
    videoId: 'L_Guz73e6fw',
    url: 'https://www.youtube.com/watch?v=L_Guz73e6fw',
    duration: '2h 02min',
    viralityScore: 94,
    reason: 'Previsões futuristas impactantes e reflexões existenciais ideais para debates quentes no TikTok.',
    suggestedThemes: ['Inteligência Artificial', 'Futuro', 'Inovação', 'Tech'],
  },
  {
    title: 'Inteligência Ltda: Especial Médicos e Cirurgiões Renomados',
    channel: 'Inteligência Ltda',
    videoId: 'qbTzhB0akt8',
    url: 'https://www.youtube.com/watch?v=qbTzhB0akt8',
    duration: '2h 50min',
    viralityScore: 96,
    reason: 'Histórias reais de suspense e adrenalina que mantêm 100% de retenção até os últimos segundos.',
    suggestedThemes: ['Saúde', 'Ciência', 'Medicina', 'Curiosidades'],
  },
  {
    title: 'The Joe Rogan Experience: Unbelievable Discoveries & Human Limits',
    channel: 'PowerfulJRE',
    videoId: '3qHkcs3kG44',
    url: 'https://www.youtube.com/watch?v=3qHkcs3kG44',
    duration: '2h 45min',
    viralityScore: 99,
    reason: 'Momentos de pura surpresa ("Mind blown"), reações viscerais e fatos inacreditáveis de fácil consumo.',
    suggestedThemes: ['Curiosidades', 'Espaço', 'História', 'Debate'],
  },
  {
    title: 'Os Sócios Podcast: Como Construir Patrimônio e Liberdade Financeira',
    channel: 'Os Sócios',
    videoId: 'B7FNkIwLbyw',
    url: 'https://www.youtube.com/watch?v=B7FNkIwLbyw',
    duration: '2h 20min',
    viralityScore: 95,
    reason: 'Dicas práticas de investimentos com alta taxa de salvamento nos Shorts.',
    suggestedThemes: ['Negócios', 'Finanças', 'Empreendedorismo'],
  },
  {
    title: 'Ironberg Podcast: Disciplina Inabalável e Superação Extrema',
    channel: 'Ironberg Podcast',
    videoId: 'xj9nNrTxlI0',
    url: 'https://www.youtube.com/watch?v=xj9nNrTxlI0',
    duration: '1h 40min',
    viralityScore: 96,
    reason: 'Choque de realidade motivacional com linguagem direta e autêntica.',
    suggestedThemes: ['Saúde', 'Motivação', 'Superação', 'Foco'],
  },
  {
    title: 'Ciência Sem Fim: Segredos do Universo e Inteligência Artificial',
    channel: 'Ciência Sem Fim',
    videoId: '5qap5aO4i9A',
    url: 'https://www.youtube.com/watch?v=5qap5aO4i9A',
    duration: '2h 40min',
    viralityScore: 94,
    reason: 'Fatos curiosos que despertam choque e fascínio imediato na audiência.',
    suggestedThemes: ['Ciência', 'Tecnologia', 'Curiosidades'],
  },
  {
    title: 'Podpah: Histórias de Superação da Periferia ao Sucesso',
    channel: 'Podpah',
    videoId: 'W7zD3q-i4vE',
    url: 'https://www.youtube.com/watch?v=W7zD3q-i4vE',
    duration: '2h 30min',
    viralityScore: 98,
    reason: 'Conversas espontâneas com alta identificação emocional e relatos envolventes.',
    suggestedThemes: ['Humor', 'Histórias', 'Superação'],
  },
  {
    title: 'Ticaracaticast: As Melhores Histórias dos Bastidores da TV',
    channel: 'Ticaracaticast',
    videoId: 'Uu2d7c58jPQ',
    url: 'https://www.youtube.com/watch?v=Uu2d7c58jPQ',
    duration: '1h 50min',
    viralityScore: 93,
    reason: 'Resenhas cômicas que prendem do início ao fim com risadas garantidas.',
    suggestedThemes: ['Comédia', 'Humor', 'Televisão'],
  },
];

export const FORMAT_OPTIONS = [
  {
    id: 'split_screen',
    label: 'Split Screen (2 Câmeras Empilhadas)',
    badge: '🔥 O Mais Viral (Podcasts)',
    desc: 'Empilha duas câmeras em proporção exata 9:8 (Convidado em cima e Host embaixo) sem achatar ou cortar rostos.',
    aspect: '9/16',
  },
  {
    id: 'dynamic_reframe',
    label: 'Auto-Reframe Dinâmico (Troca de Câmera IA)',
    badge: '🤖 Klap / Opus AI',
    desc: 'Alterna automaticamente a câmera em tela cheia 9:16 entre quem está falando e quem reage usando as coordenadas faciais da IA.',
    aspect: '9/16',
  },
  {
    id: 'speaker_left',
    label: 'Foco no Apresentador (Câmera 1 / Esquerda)',
    badge: 'Host / Câmera 1',
    desc: 'Enquadra em tela cheia 9:16 a coordenada exata do participante à esquerda detectado pela IA Vision.',
    aspect: '9/16',
  },
  {
    id: 'speaker_right',
    label: 'Foco no Convidado (Câmera 2 / Direita)',
    badge: 'Convidado / Câmera 2',
    desc: 'Enquadra em tela cheia 9:16 a coordenada exata do convidado à direita detectado pela IA Vision.',
    aspect: '9/16',
  },
  {
    id: 'vertical_blur',
    label: 'Vertical 9:16 - Fundo Desfocado Cinemático',
    badge: '100% Seguro',
    desc: 'Mantém o quadro 16:9 completo no centro com fundo desfocado elegante nas barras superior e inferior.',
    aspect: '9/16',
  },
  {
    id: 'speaker_center',
    label: 'Foco Central (Solo / Monólogo)',
    badge: 'Monólogo',
    desc: 'Enquadramento vertical 9:16 centralizado para vídeos individuais, aulas ou palestras.',
    aspect: '9/16',
  },
  {
    id: 'vertical_crop',
    label: 'Vertical 9:16 - Recorte Central Clássico',
    badge: 'Padrão',
    desc: 'Recorta as laterais em proporção 9:16 mantendo o centro exato do vídeo sem distorção.',
    aspect: '9/16',
  },
  {
    id: 'original',
    label: 'Original 16:9 - Widescreen',
    badge: 'Horizontal',
    desc: 'Mantém a proporção horizontal original do YouTube sem cortes ou distorções.',
    aspect: '16/9',
  },
  {
    id: 'square',
    label: 'Quadrado 1:1 - Feed Social',
    badge: 'Instagram Feed',
    desc: 'Formato clássico 1:1 perfeito para carrosséis e posts de feed no Instagram ou LinkedIn.',
    aspect: '1/1',
  },
] as const;

export const SUBTITLE_THEMES = [
  {
    id: 'hormozi',
    name: 'Alex Hormozi',
    color: '#FACC15', // Yellow
    accent: '#000000',
    desc: 'Texto branco em caixa alta com palavras de choque destacadas em amarelo e borda preta grossa.',
  },
  {
    id: 'beast',
    name: 'MrBeast',
    color: '#22C55E', // Green
    accent: '#000000',
    desc: 'Verde neon vibrante com alta saturação e ganchos dinâmicos de retenção acelerada.',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    color: '#EC4899', // Pink / Magenta
    accent: '#7C3AED',
    desc: 'Fúcsia e roxo de alto contraste para vídeos de tecnologia, IA e mistério.',
  },
  {
    id: 'clean',
    name: 'Clean Minimal',
    color: '#FFFFFF', // White
    accent: '#18181B',
    desc: 'Branco elegante com sombra suave e estilo discreto para negócios e finanças.',
  },
] as const;
